### ISSUE TITLE
Increment and decrement methods for Integer trait?

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-integer#2]
_From @L117 on June 22, 2017 9:55_

When dealing with primitive integers it's fast and easy to increment/decrement with `x += 1;`/`x -= 1;`, but with `BigInt`/`BigUint` it wastes an allocation and/or becomes tedious (Imagine calling `One::one`, `From::from` and defining `static ONE`). So such methods could come in handy.

_Copied from original issue: rust-num/num#307_

**Comment by cuviper** [comment]
Sure, that could be useful.

The trait will have to provide default implementations in order for this to not be a breaking change, which means it probably has to require `Clone`.  e.g. `*self = self.clone() + Self::one()`.  But that's harmless for primitives and can be overridden in types like the bigints.

**Comment by danieleades** [comment]
this would be really handy

**Comment by danieleades** [comment]
I've just discovered the [`Step`](https://doc.rust-lang.org/std/iter/trait.Step.html)

**Comment by cuviper** [comment]
It would be a breaking change for `Integer` to require `Step`, and also that trait is still unstable.

**Comment by cuviper** [comment]
Closed by #53
