### ISSUE TITLE
Why hiding field of ExtendedGcd?

### ISSUE THREAD

**Issue by survived** [rust-num/num-integer#39]
Noticed that there's no way to construct ExtendedGcd from user code (because of [hidden field](https://docs.rs/num-integer/0.1.44/src/num_integer/lib.rs.html#359)), and I can't implement `Integer::extended_gcd` (as I can't construct being returned structure) and I have to use your generic implementation of egcd. Perhaps there should be `ExtendedGcd::new()` constructor?

**Comment by cuviper** [comment]
It's just meant as an approximation of the newer `#[non_exhaustive]` attribute, allowing the possibility of new fields in the future. I'm not sure what else we would want to add though, so maybe we should just remove the hidden field and let it be done.

**Comment by survived** [comment]
Yep, removing this field makes sense

**Comment by tspiteri** [comment]
I hit this when trying to implement `num_integer::Integer` for `rug::Integer`, and had to use a [very ugly hack](https://gitlab.com/tspiteri/rug/-/blob/4afff68b061fc03ce722044f38529e35bb3cba5c/src/integer/impl_num_traits.rs#L386-L499) complete with transmute to create an `ExtendedGcd` struct.
